[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.30.3"
ci = "github"
installers = ["shell", "powershell"]
targets = [
  "aarch64-unknown-linux-gnu",
  "aarch64-apple-darwin",
]
pr-run-mode = "plan"
install-updater = false
install-path = "CARGO_HOME"
github-build-setup = "../cargo-dist-build-setup.yml"

[dist.github-custom-runners.aarch64-unknown-linux-gnu]
runner = "ubuntu-22.04-arm"
